services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - frontend-cache:/app/node_modules/.cache
    command: npm run dev
    networks:
      - app-network

volumes:
  node_modules:
  frontend-cache:  

networks:
  app-network:
    driver: bridge